source_file:
 path: "/home/tiphainell/Documents/3.Energy_RTE/data_processed"
 column_power_name: "Consommation"
 column_timestamps: "timestamp"

task:
 hourly_horizon: 24
 step_per_hour: 4


model:
 name: "xgboost"
 max_depth: 10
 n_estimators: 10


split_train_test:
 date_split: "2023-05-01"








